# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-11 04:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import storages.backends.ftp


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interestname', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('username', models.CharField(max_length=20)),
                ('nickname', models.CharField(default='', max_length=20)),
                ('sign', models.CharField(default='这个人很懒，什么都没有留下', max_length=500)),
                ('score', models.IntegerField(default=0)),
                ('level', models.CharField(default='实习小编', max_length=20)),
                ('headpic', models.ImageField(storage=storages.backends.ftp.FTPStorage(), upload_to='headpic')),
                ('interest', models.ManyToManyField(to='user.Interest')),
            ],
        ),
        migrations.CreateModel(
            name='UserScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('type', models.CharField(max_length=5)),
                ('score', models.IntegerField()),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
