# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-13 15:18
from __future__ import unicode_literals

from django.db import migrations, models
import storages.backends.ftp


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='headpic',
            field=models.ImageField(null=True, storage=storages.backends.ftp.FTPStorage(), upload_to='headpic'),
        ),
    ]
