# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-11 04:34
from __future__ import unicode_literals

import ckeditor.fields
import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('auther', models.CharField(max_length=20)),
                ('title', models.TextField(max_length=50)),
                ('text', ckeditor_uploader.fields.RichTextUploadingField()),
                ('text2', ckeditor.fields.RichTextField()),
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('mod_date', models.DateTimeField(auto_now=True)),
                ('comment_count', models.IntegerField(default=0)),
                ('seen_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ArticleComment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('commenter', models.CharField(max_length=20)),
                ('comment_text', models.CharField(max_length=200)),
                ('comment_date', models.DateTimeField(auto_now_add=True)),
                ('comment_up_count', models.IntegerField(default=0)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Article')),
            ],
        ),
        migrations.CreateModel(
            name='CommentUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_uper', models.CharField(max_length=100)),
                ('is_comment', models.NullBooleanField()),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.ArticleComment')),
            ],
        ),
    ]
