# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-08 03:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_articlecomment_userinfo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comment_up',
            new_name='CommentUp',
        ),
    ]
